# Generated by Django 3.2.8 on 2021-10-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome', max_length=100)),
                ('aniversario', models.DateField(help_text='Aniversário')),
                ('email', models.EmailField(help_text='e-mail', max_length=254)),
                ('fone', models.CharField(help_text='Telefone', max_length=11)),
            ],
        ),
    ]
