# Generated by Django 3.2.8 on 2021-10-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicos', '0002_alter_servico_tempo'),
        ('Funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.DateTimeField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('profissinal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Funcionarios.funcionario')),
                ('servicos', models.ManyToManyField(to='servicos.Servico')),
            ],
        ),
    ]
