# Generated by Django 3.2.8 on 2021-10-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='clientes',
            new_name='cliente',
        ),
    ]
