# Generated by Django 3.2.8 on 2021-10-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='tempo',
            field=models.DurationField(),
        ),
    ]
